language: python
python:
- 3.6

services:
  - docker
  
install:
  - pip install -r requirements.txt

script:
  - coverage run tests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker build -t cps847/myfirstrepo
  - docker run -d -p 5000:5000 cps847/myfirstrepo /bin/sh
  - docker ps -a 

 
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY_ID
  region: us-east-2
  app: "helloworld"
  env: "helloworld-env"
  bucket_name: "elasticbeanstalk-us-east-2-561357807659"
  local_dir: deployment completed 
  on:
    branch: main
    
after_deploy:
  - echo "deployment completed"
